[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --no-stub"

[env]
ESP_LOG="DEBUG"
ESP_WIFI_CONFIG_COUNTRY_CODE="US"
ESP_WIFI_CONFIG_PHY_ENABLE_USB="true"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
