name: Arduino Sensor

on: [push]

jobs:

  compile-sensor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.1

    - name: Setup Environment
      run: |
        arduino-cli config init
        arduino-cli core update-index
        arduino-cli core update-index --additional-urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
        arduino-cli core install adafruit:samd --additional-urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json

    - name: Compile Sensor
      run: |
        arduino-cli config set library.enable_unsafe_install true
        arduino-cli lib install --git-url https://github.com/adafruit/RadioHead.git
        arduino-cli lib install "Adafruit EPD"
        arduino-cli lib install "Adafruit SGP30 Sensor"
        arduino-cli lib install "Adafruit SHT4x Library"
        arduino-cli lib install "Arduino Low Power"
        arduino-cli compile --fqbn adafruit:samd:adafruit_feather_m0 Sensor
