name: Pull Request

on:

  pull_request:
    branches:
      - main

jobs:

  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v2.0.0

  rust-esp32c6:
    uses: "philipcristiano/workflows/.github/workflows/rust.yml@main"
    with:
      working-directory: esp32c6-sensor
      setup_script: |
          rustup target add riscv32imac-unknown-none-elf

  flake-esp32c6:
    uses: "philipcristiano/workflows/.github/workflows/nix.yml@main"
    with:
      flakes-from-devshell: true
      script: |
        cd esp32c6-sensor; cargo build
